const translations = {
  en: {
    updateAvailable: "🔄 Update available — tap to reload",
    searchPlaceholder: "Search: title, artist or genre",
    searchLyricsPlaceholder: "Search: lyrics",
    allGenres: "All genres",
    showMusic: "Show",
    sortDefault: "📅 Default",
    sortPlaysDesc: "▲ Plays",
    sortPlaysAsc: "▼ Plays",
    sortLikesDesc: "▲ Likes",
    sortLikesAsc: "▼ Likes",
    sortTitleAsc: "A-Z Title",
    sortTitleDesc: "Z-A Title",
    dragToReorder: "Drag tracks to reorder",
    uploadTrack: "⬆ Upload Track",
    uploadPartnerTrack: "🎧 Upload your song",
    exportJson: "📦 Export JSON",
    resetPlays: "🔄 Reset Plays",
    uploadAdminOnly: "I upload only",
    uploadPartnerOnly: "Me + second person",
    uploadEveryone: "Everyone can upload",
    loadingTracks: "⏳ Loading tracks...",
    sequential: "Sequential 🔁",
    random: "Random 🔀",
    volume: "Volume",
    text: "📄",
    comments: "Comments",
    share: "Share",
    download: "Download",
    close: "Close",
    cancel: "Cancel",
    send: "Send",
    save: "💾 Save",
    copy: "📋 Copy",
    copied: "✅ Copied!",
    edit: "✏️ Edit",
    addTrack: "Add Track",
    trackTitle: "Track title",
    mp3Link: "MP3 link (GitHub raw)",
    coverUrl: "Cover image URL",
    genres: "Genres",
    lyrics: "Lyrics",
    fullText: "Full text",
    noComments: "No comments",
    writeComment: "Write a comment...",
    deleteConfirm: "Delete this comment?",
    commentSaved: "💬 Comment saved!",
    commentError: "❌ Comment save error",
    noTracks: "No tracks",
    createFile: "Create <code>tracks.json</code> file in repository root",
    orAdd: "Or add via <strong>?admin</strong>",
    required: "Title, MP3 and cover are required",
    exported: "Exported",
    tracks: "tracks!",
    uploadGithub: "Upload tracks.json to GitHub",
    refreshPage: "Refresh page on all devices",
    plays: "plays",
    playlists: "Playlists",
    myTracks: "My Tracks",
    allTracks: "All Tracks",
    playlistName: "Playlist name",
    createPlaylist: "Create Playlist",
    addToPlaylist: "Add to Playlist",
    removeFromPlaylist: "Remove from Playlist",
    visibility: "Visibility",
    public: "🌍 Public",
    partner: "♥ Partner only",
    hidden: "🔒 Hidden (only me)",
    songsInPlaylist: "songs",
    changeCover: "Change Cover",
    addSongsToPlaylist: "Add Songs to Playlist",
    selectPlaylist: "Select Playlist",
    noPlaylists: "No playlists yet",
    likedSongs: "❤️ Liked Songs",
    showLikedOnly: "Show Liked Only",
    showAll: "Show All",
    deletePlaylist: "Delete Playlist",
    deletePlaylistConfirm: "Delete this playlist? Songs will remain on the site.",
    songVisibility: "Song Visibility",
    showToAll: "Show to All",
    showToMe: "Show Only to Me",
    showToPartner: "Show to Me & Partner",
    userUpload: "Upload your song",
    uploadYourSong: "Upload your song",
    songTitle: "Title",
    songArtist: "Artist",
    songGenre: "Genre",
    upload: "Upload",
    deleteTrack: "Delete track",
    replaceTrackFiles: "🔄 Replace track files",
    statsWillStay: "Statistics (likes, plays) will be preserved",
    newMp3Optional: "New MP3 file (optional)",
    newCoverOptional: "New cover image (optional)",
    replace: "Replace",
    enter: "Enter",
    login: "Login",
    logout: "Logout",
    newTracksShort: "NEW",
    uploadShort: "Upload",
    filterAllSongs: "🎧 All songs",
    filterMySongs: "👤 My songs",
    filterPartner: "💑 Partner",
    filterHidden: "🔒 Hidden from all",
    filterPartnerOnly: "♥ Partner only",
    filterAdmin: "👑 Admin",
    filterPartnerOnlyMe: "🔒 Only for me",
    multiSelect: "Multi-select",
    uploadSuccess: "✅ Song uploaded!",
    uploadError: "❌ Error: ",
    uploading: "⏳ Uploading...",
    uploadBtn: "Upload",
    likedTracks: "Liked",
    downloadRestricted: "Download Restricted",
    downloadRestrictedText: "Track download is available only for registered users",
    login: "Login",
    createAccount: "Create Account",
    create: "Create",
    email: "Email",
    password: "Password",
    passwordMin: "Password (min 6 chars)",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    sendResetEmail: "Send Reset Email",
    backToLogin: "Back to Login",
    searchGenre: "Search genre",
    searchTracks: "Search tracks...",
    coverImage: "Cover image",
    darkGradient: "Dark gradient",
    purpleGradient: "Purple gradient",
    blueGradient: "Blue gradient",
    greenGradient: "Green gradient",
    orangeGradient: "Orange gradient",
    pinkGradient: "Pink gradient",
    solidColor: "Solid color",
    hideTracksFromHome: "Hide tracks from home page",
    hiddenFromHome: "Hidden from home",
    addTracksToPlaylist: "Add tracks to playlist",
    selectAll: "Select all",
    addSelected: "Add selected",
    previous: "Previous",
    next: "Next",
    playPause: "Play/Pause",
    openFullText: "Open full text",
    like: "Like",
    dislike: "Dislike",
    visualizer: "Visualizer",
    shareTrack: "Share Track",
    copyLink: "Copy Link",
    copyToClipboard: "Copy to clipboard",
    shareTo: "Share to",
    noLyrics: "No lyrics",
    anonymous: "Anonymous",
    writeCommentFirst: "Write a comment first",
    errorSendingComment: "Error sending comment",
    saveFailed: "Save failed",
    failedToSaveLyrics: "Failed to save lyrics",
    playlistIdMissing: "Playlist ID missing",
    playlistNotFound: "Playlist not found",
    deleteTrackConfirm: "Delete track \"%s\"? Files will also be deleted from Cloudflare.",
    text: "📄",
    uploaded: "Uploaded",
    added: "Added",
    noTracksAvailable: "No tracks available to add",
    onlyAddOwnPlaylist: "You can only add tracks to playlists you created",
    notAllowedModify: "You are not allowed to modify this playlist",
    noPermissionModify: "You do not have permission to modify this playlist",
    failedFetchPlaylist: "Failed to fetch playlist",
    failedOpenPlaylist: "Failed to open playlist",
    failedLoadTracks: "Failed to load tracks",
    noTracksSelected: "No tracks selected",
    noPlaylistSelected: "No playlist selected",
    alreadyInPlaylist: "Selected tracks are already in this playlist",
    addFailed: "Add failed — check console for details",
    removeTrackConfirm: "Remove this track from playlist?",
    removeFailed: "Remove failed",
    selectOneField: "Select at least one field to change",
    filesReplaced: "Files replaced successfully!",
    replaceError: "Replace error",
    uploadFailed: "Upload failed",
    noTrackSelected: "No track selected",
    webShareNotSupported: "Web Share not supported",
    checkOut: "Check out",
    track: "Track",
    downloadFailed: "Download failed",
    audioNotFound: "Audio not found",
    downloadError: "Download error",
    updateFailed: "Update failed",
    comment: "Comment",
    emoji: "Emoji",
    loading: "Loading",
    trackName: "Track Name",
    title: "Title",
    home: "Home",
    background: "Background",
    add: "Add",
    likedTracks: "Liked",
    feedback: "Feedback",
    feedbackTitle: "Feedback",
    feedbackSubtitle: "Send us a suggestion, report a bug, or share your thoughts",
    feedbackType: "Message type",
    feedbackSuggestion: "💡 Suggestion",
    feedbackRecommendation: "⭐ Recommendation",
    feedbackBug: "🐛 Bug",
    feedbackOther: "❓ Other",
    feedbackMessage: "Message *",
    feedbackEmail: "Email (optional)",
    feedbackSubmit: "Send",
    myFeedback: "My Feedback",
    feedbackHistory: "Feedback History",
    feedbackHistorySubtitle: "Your sent messages and responses",
    noFeedback: "No messages",
    statusUnread: "🔴 Unread",
    statusInProgress: "🟠 In progress",
    statusDone: "🟢 Done",
    statusRejected: "⚪ Rejected",
    statusRead: "💜 Read",
    allFeedback: "All Feedback",
    feedbackSent: "✅ Message sent! Thank you for your feedback.",
    feedbackError: "❌ Error sending. Try again later.",
    feedbackRequired: "❌ Please write a message",
    feedbackSending: "Sending...",
    deleteFeedbackConfirm: "Delete this message?",
    deleteFeedbackError: "Error deleting",
    updateStatusError: "Error updating status",
    loadingHistoryError: "Error loading history",
    feedbackSuggestion: "💡 Suggestion",
    feedbackRecommendation: "⭐ Recommendation",
    feedbackBug: "🐛 Bug",
    feedbackOther: "❓ Other",
    feedbackPlaceholder: "Describe your thought...",
    feedbackRestrictedTitle: "🔒 Access restricted",
    feedbackRestrictedText: "Submitting feedback is available only for registered users.",
    feedbackRestrictedLogin: "Log in",
    feedbackRestrictedClose: "Close",

  },
  pl: {
    updateAvailable: "🔄 Dostępna aktualizacja — kliknij, aby odświeżyć",
    searchPlaceholder: "Szukaj: tytuł, artysta lub gatunek",
    searchLyricsPlaceholder: "Szukaj: tekst piosenki",
    allGenres: "Wszystkie gatunki",
    showMusic: "Pokaż",
    sortDefault: "📅 Domyślnie",
    sortPlaysDesc: "▲ Odtworzenia",
    sortPlaysAsc: "▼ Odtworzenia",
    sortLikesDesc: "▲ Polubienia",
    sortLikesAsc: "▼ Polubienia",
    sortTitleAsc: "A-Z Tytuł",
    sortTitleDesc: "Z-A Tytuł",
    dragToReorder: "Przeciągnij utwory, aby zmienić kolejność",
    uploadTrack: "⬆ Dodaj utwór",
    uploadPartnerTrack: "🎧 Dodaj swoją piosenkę",
    exportJson: "📦 Eksportuj JSON",
    resetPlays: "🔄 Resetuj Odsłuchy",
    uploadAdminOnly: "Dodaje tylko ja",
    uploadPartnerOnly: "Ja + druga osoba",
    uploadEveryone: "Moga dodawac wszyscy",
    loadingTracks: "⏳ Ładowanie utworów...",
    sequential: "Kolejno 🔁",
    random: "Losowo 🔀",
    volume: "Głośność",
    text: "📄",
    comments: "Komentarze",
    share: "Udostępnij",
    download: "Pobierz",
    close: "Zamknij",
    cancel: "Anuluj",
    send: "Wyślij",
    save: "💾 Zapisz",
    copy: "📋 Kopiuj",
    copied: "✅ Skopiowano!",
    edit: "✏️ Edytuj",
    addTrack: "Dodaj utwór",
    trackTitle: "Tytuł utworu",
    mp3Link: "Link do MP3 (GitHub raw)",
    coverUrl: "Adres URL okładki",
    genres: "Gatunki",
    lyrics: "Tekst piosenki",
    fullText: "Pełny tekst",
    noComments: "Brak komentarzy",
    writeComment: "Napisz komentarz...",
    deleteConfirm: "Usunąć ten komentarz?",
    commentSaved: "💬 Komentarz zapisany!",
    commentError: "❌ Błąd zapisu komentarza",
    noTracks: "Brak utworów",
    createFile: "Utwórz plik <code>tracks.json</code> w katalogu głównym",
    orAdd: "Lub dodaj przez <strong>?admin</strong>",
    required: "Tytuł, MP3 i okładka są wymagane",
    exported: "Wyeksportowano",
    tracks: "utworów!",
    uploadGithub: "Prześlij tracks.json do GitHub",
    refreshPage: "Odśwież stronę na wszystkich urządzeniach",
    plays: "odtworzeń",
    playlists: "Playlisty",
    myTracks: "Moje utwory",
    allTracks: "Wszystkie utwory",
    playlistName: "Nazwa listy",
    createPlaylist: "Utwórz Listę",
    addToPlaylist: "Dodaj do listy",
    removeFromPlaylist: "Usuń z listy",
    visibility: "Widoczność",
    public: "🌍 Publiczna",
    partner: "♥ Tylko dla partnera",
    hidden: "🔒 Ukryta (tylko ja)",
    songsInPlaylist: "utworów",
    changeCover: "Zmień okładkę",
    addSongsToPlaylist: "Dodaj utwory do listy",
    selectPlaylist: "Wybierz listę",
    noPlaylists: "Brak list odtwarzania",
    likedSongs: "❤️ Polubione utwory",
    showLikedOnly: "Pokaż tylko polubione",
    showAll: "Pokaż wszystkie",
    deletePlaylist: "Usuń listę",
    deletePlaylistConfirm: "Usunąć tę listę? Utwwory pozostaną na stronie.",
    songVisibility: "Widoczność utworu",
    showToAll: "Pokaż wszystkim",
    showToMe: "Pokaż tylko mnie",
    showToPartner: "Pokaż mnie i partnera",
    userUpload: "Dodaj swoją piosenkę",
    uploadYourSong: "Dodaj swoją piosenkę",
    songTitle: "Tytuł",
    songArtist: "Autor",
    songGenre: "Gatunek",
    upload: "Dodaj",
    replaceTrackFiles: "🔄 Zmień pliki utworu",
    statsWillStay: "Statystyki (polubienia, odsłuchy) zostaną zachowane",
    newMp3Optional: "Nowy plik MP3 (opcjonalnie)",
    newCoverOptional: "Nowa okładka (opcjonalnie)",
    replace: "Zmień",
    deleteTrack: "Usuń utwór",
    enter: "Wejdź",
    login: "Zaloguj",
    logout: "Wyloguj",
    newTracksShort: "NOWE",
    uploadShort: "Dodaj",
    filterAllSongs: "🎧 Wszystkie",
    filterMySongs: "👤 Moje",
    filterPartner: "💑 Partner",
    filterHidden: "🔒 Ukryte",
    filterPartnerOnly: "♥ Tylko partner",
    filterAdmin: "👑 Admin",
    filterPartnerOnlyMe: "🔒 Tylko dla mnie",
    multiSelect: "Wielokrotny wybór",
    uploadSuccess: "✅ Piosenka dodana!",
    uploadError: "❌ Błąd: ",
    uploading: "⏳ Dodawanie...",
    uploadBtn: "Dodaj",
    likedTracks: "Polubione",
    downloadRestricted: "Pobieranie ograniczone",
    downloadRestrictedText: "Pobieranie utworów dostępne tylko dla zarejestrowanych użytkowników",
    login: "Zaloguj się",
    createAccount: "Utwórz konto",
    create: "Utwórz",
    email: "Email",
    password: "Hasło",
    passwordMin: "Hasło (min 6 znaków)",
    confirmPassword: "Potwierdź hasło",
    forgotPassword: "Zapomniałeś hasła?",
    sendResetEmail: "Wyślij email resetujący",
    backToLogin: "Powrót do logowania",
    searchGenre: "Szukaj gatunku",
    searchTracks: "Szukaj utworów...",
    coverImage: "Okładka",
    darkGradient: "Ciemny gradient",
    purpleGradient: "Fioletowy gradient",
    blueGradient: "Niebieski gradient",
    greenGradient: "Zielony gradient",
    orangeGradient: "Pomarańczowy gradient",
    pinkGradient: "Różowy gradient",
    solidColor: "Jednolity kolor",
    hideTracksFromHome: "Ukryj utwory ze strony głównej",
    hiddenFromHome: "Ukryte ze strony głównej",
    addTracksToPlaylist: "Dodaj utwory do listy",
    selectAll: "Zaznacz wszystko",
    addSelected: "Dodaj zaznaczone",
    previous: "Poprzedni",
    next: "Następny",
    playPause: "Odtwórz/Pauza",
    openFullText: "Otwórz pełny tekst",
    like: "Polub",
    dislike: "Nie lubię",
    visualizer: "Wizualizator",
    shareTrack: "Udostępnij utwór",
    copyLink: "Kopiuj link",
    copyToClipboard: "Kopiuj do schowka",
    shareTo: "Udostępnij w",
    noLyrics: "Brak tekstu",
    anonymous: "Anonimowy",
    writeCommentFirst: "Napisz najpierw komentarz",
    errorSendingComment: "Błąd wysyłania komentarza",
    saveFailed: "Zapis nie powiódł się",
    failedToSaveLyrics: "Nie udało się zapisać tekstu",
    playlistIdMissing: "Brak ID listy odtwarzania",
    playlistNotFound: "Nie znaleziono listy",
    deleteTrackConfirm: "Usunąć utwór \"%s\"? Pliki zostaną usunięte z Cloudflare.",
    text: "📄",
    uploaded: "Dodano",
    added: "Dodano",
    noTracksAvailable: "Brak dostępnych utworów do dodania",
    onlyAddOwnPlaylist: "Możesz dodawać utwory tylko do własnych list",
    notAllowedModify: "Nie masz uprawnień do modyfikacji tej listy",
    noPermissionModify: "Nie masz uprawnień do modyfikacji tej listy",
    failedFetchPlaylist: "Nie udało się pobrać listy",
    failedOpenPlaylist: "Nie udało się otworzyć listy",
    failedLoadTracks: "Nie udało się załadować utworów",
    noTracksSelected: "Nie wybrano utworów",
    noPlaylistSelected: "Nie wybrano listy",
    alreadyInPlaylist: "Wybrane utwory są już na tej liście",
    addFailed: "Dodawanie nie powiodło się — sprawdź konsolę",
    removeTrackConfirm: "Usunąć ten utwór z listy?",
    removeFailed: "Usuwanie nie powiodło się",
    selectOneField: "Wybierz przynajmniej jedno pole do zmiany",
    filesReplaced: "Pliki zostały zamienione!",
    replaceError: "Błąd zamiany",
    uploadFailed: "Przesyłanie nie powiodło się",
    noTrackSelected: "Nie wybrano utworu",
    webShareNotSupported: "Udostępnianie nie jest obsługiwane",
    checkOut: "Sprawdź",
    track: "Utwór",
    downloadFailed: "Pobieranie nie powiodło się",
    audioNotFound: "Nie znaleziono audio",
    downloadError: "Błąd pobierania",
    updateFailed: "Aktualizacja nie powiodła się",
    comment: "Komentarz",
    emoji: "Emoji",
    loading: "Ładowanie",
    trackName: "Nazwa utworu",
    title: "Tytuł",
    home: "Strona główna",
    background: "Tło",
    add: "Dodaj",
    likedTracks: "Polubione",
    feedback: "Opinie",
    feedbackTitle: "Opinie",
    feedbackSubtitle: "Wyślij nam sugestię, zgłoś błąd lub podziel się swoimi przemyśleniami",
    feedbackType: "Typ wiadomości",
    feedbackSuggestion: "💡 Sugestia",
    feedbackRecommendation: "⭐ Rekomendacja",
    feedbackBug: "🐛 Błąd",
    feedbackOther: "❓ Inne",
    feedbackMessage: "Wiadomość *",
    feedbackEmail: "Email (opcjonalnie)",
    feedbackSubmit: "Wyślij",
    myFeedback: "Moje opinie",
    feedbackHistory: "Historia opinii",
    feedbackHistorySubtitle: "Twoje wysłane wiadomości i odpowiedzi",
    noFeedback: "Brak wiadomości",
    statusUnread: "🔴 Nieprzeczytane",
    statusInProgress: "🟠 W trakcie",
    statusDone: "🟢 Zrobione",
    statusRejected: "⚪ Odrzucone",
    statusRead: "💜 Przeczytane",
    allFeedback: "Wszystkie opinie",
    feedbackSent: "✅ Wiadomość wysłana! Dziękujemy za opinię.",
    feedbackError: "❌ Błąd wysyłania. Spróbuj później.",
    feedbackRequired: "❌ Napisz wiadomość",
    feedbackSending: "Wysyłanie...",
    deleteFeedbackConfirm: "Usunąć tę wiadomość?",
    deleteFeedbackError: "Błąd usuwania",
    updateStatusError: "Błąd aktualizacji statusu",
    loadingHistoryError: "Błąd ładowania historii",
    feedbackSuggestion: "💡 Sugestia",
    feedbackRecommendation: "⭐ Rekomendacja",
    feedbackBug: "🐛 Błąd",
    feedbackOther: "❓ Inne",
    feedbackPlaceholder: "Opisz swoją myśl...",
    feedbackRestrictedTitle: "🔒 Dostęp ograniczony",
    feedbackRestrictedText: "Wysyłanie opinii jest dostępne tylko dla zalogowanych użytkowników.",
    feedbackRestrictedLogin: "Zaloguj się",
    feedbackRestrictedClose: "Zamknij",

  },
  ua: {
    updateAvailable: "🔄 Доступне оновлення — натисніть, щоб перезавантажити",
    searchPlaceholder: "Пошук: назва, виконавець або жанр",
    searchLyricsPlaceholder: "Пошук: текст пісні",
    allGenres: "Усі жанри",
    showMusic: "Показати",
    sortDefault: "📅 За замовчуванням",
    sortPlaysDesc: "▲ Прослуховування",
    sortPlaysAsc: "▼ Прослуховування",
    sortLikesDesc: "▲ Лайки",
    sortLikesAsc: "▼ Лайки",
    sortTitleAsc: "А-Я Назва",
    sortTitleDesc: "Я-А Назва",
    dragToReorder: "Перетягніть треки для зміни порядку",
    uploadTrack: "⬆ Завантажити трек",
    uploadPartnerTrack: "🎧 Завантажити свою пісню",
    exportJson: "📦 Експорт JSON",
    resetPlays: "🔄 Скинути Оглядання",
    uploadAdminOnly: "Завантажує тільки я",
    uploadPartnerOnly: "Я + друга особа",
    uploadEveryone: "Можуть завантажувати всі",
    loadingTracks: "⏳ Завантаження треків...",
    sequential: "По порядку 🔁",
    random: "Випадково 🔀",
    volume: "Гучність",
    text: "📄",
    comments: "Коментарі",
    share: "Поділитися",
    download: "Завантажити",
    close: "Закрити",
    cancel: "Скасувати",
    send: "Надіслати",
    save: "💾 Зберегти",
    copy: "📋 Копіювати",
    copied: "✅ Скопійовано!",
    edit: "✏️ Редагувати",
    addTrack: "Додати трек",
    trackTitle: "Назва треку",
    mp3Link: "Посилання на MP3 (GitHub raw)",
    coverUrl: "URL обкладинки",
    genres: "Жанри",
    lyrics: "Текст пісні",
    fullText: "Повний текст",
    noComments: "Немає коментарів",
    writeComment: "Напишіть коментар...",
    deleteConfirm: "Видалити цей коментар?",
    commentSaved: "💬 Коментар збережено!",
    commentError: "❌ Помилка збереження",
    noTracks: "Немає треків",
    createFile: "Створіть файл <code>tracks.json</code> у кореневій директорії",
    orAdd: "Або додайте через <strong>?admin</strong>",
    required: "Назва, MP3 та обкладинка обов'язкові",
    exported: "Експортовано",
    tracks: "треків!",
    uploadGithub: "Завантажте tracks.json на GitHub",
    refreshPage: "Оновіть сторінку на всіх пристроях",
    plays: "відтворень",
    playlists: "Плейлисти",
    myTracks: "Мої треки",
    allTracks: "Всі треки",
    playlistName: "Назва плейлиста",
    createPlaylist: "Створити плейлист",
    addToPlaylist: "Додати до плейлиста",
    removeFromPlaylist: "Видалити з плейлиста",
    visibility: "Видимість",
    public: "🌍 Публічний",
    partner: "♥ Тільки для партнера",
    hidden: "🔒 Прихований (лише я)",
    songsInPlaylist: "пісень",
    changeCover: "Змінити обкладинку",
    addSongsToPlaylist: "Додати пісні до плейлиста",
    selectPlaylist: "Виберіть плейлист",
    noPlaylists: "Плейлистів поки немає",
    likedSongs: "❤️ Улюблені пісні",
    showLikedOnly: "Показати лише улюблені",
    showAll: "Показати всі",
    deletePlaylist: "Видалити плейлист",
    deletePlaylistConfirm: "Видалити цей плейлист? Пісні залишаться на сайті.",
    songVisibility: "Видимість пісні",
    showToAll: "Показати всім",
    showToMe: "Показати лише мені",
    showToPartner: "Показати мені та партнеру",
    userUpload: "Завантажити свою пісню",
    uploadYourSong: "Завантажити свою пісню",
    songTitle: "Назва",
    songArtist: "Автор",
    songGenre: "Жанр",
    upload: "Завантажити",
    replaceTrackFiles: "🔄 Замінити файли треку",
    deleteTrack: "Видалити трек",
    statsWillStay: "Статистика (лайки, прослуховування) збережеться",
    newMp3Optional: "Новий MP3 файл (опціонально)",
    newCoverOptional: "Нове фото обкладинки (опціонально)",
    replace: "Замінити",
    enter: "Увійти",
    login: "Увійти",
    logout: "Вийти",
    newTracksShort: "НОВІ",
    uploadShort: "Додати",
    filterAllSongs: "🎧 Всі пісні",
    filterMySongs: "👤 Мої пісні",
    filterPartner: "💑 Партнер",
    filterHidden: "🔒 Приховані від всіх",
    filterPartnerOnly: "♥ Видно тільки партнеру",
    filterAdmin: "👑 Адмін",
    filterPartnerOnlyMe: "🔒 Тільки для мене",
    multiSelect: "Мультивибір",
    uploadSuccess: "✅ Пісню завантажено!",
    uploadError: "❌ Помилка: ",
    uploading: "⏳ Завантаження...",
    uploadBtn: "Завантажити",
    likedTracks: "Улюблені",
    downloadRestricted: "Завантаження обмежено",
    downloadRestrictedText: "Завантаження треків доступне тільки для зареєстрованих користувачів",
    login: "Увійти",
    createAccount: "Створити акаунт",
    create: "Створити",
    email: "Email",
    password: "Пароль",
    passwordMin: "Пароль (мін 6 символів)",
    confirmPassword: "Підтвердьте пароль",
    forgotPassword: "Забули пароль?",
    sendResetEmail: "Надіслати email для скидання",
    backToLogin: "Повернутися до входу",
    searchGenre: "Пошук жанру",
    searchTracks: "Пошук треків...",
    coverImage: "Обкладинка",
    darkGradient: "Темний градієнт",
    purpleGradient: "Фіолетовий градієнт",
    blueGradient: "Синій градієнт",
    greenGradient: "Зелений градієнт",
    orangeGradient: "Помаранчевий градієнт",
    pinkGradient: "Рожевий градієнт",
    solidColor: "Суцільний колір",
    hideTracksFromHome: "Приховати треки з головної сторінки",
    hiddenFromHome: "Приховано з головної",
    addTracksToPlaylist: "Додати треки до плейлиста",
    selectAll: "Вибрати все",
    addSelected: "Додати вибрані",
    previous: "Попередній",
    next: "Наступний",
    playPause: "Грати/Пауза",
    openFullText: "Відкрити повний текст",
    like: "Подобається",
    dislike: "Не подобається",
    visualizer: "Візуалізатор",
    shareTrack: "Поділитися треком",
    copyLink: "Копіювати посилання",
    copyToClipboard: "Копіювати в буфер",
    shareTo: "Поділитися в",
    noLyrics: "Немає тексту",
    anonymous: "Анонім",
    writeCommentFirst: "Спочатку напишіть коментар",
    errorSendingComment: "Помилка надсилання коментаря",
    saveFailed: "Збереження не вдалося",
    failedToSaveLyrics: "Не вдалося зберегти текст",
    playlistIdMissing: "Відсутній ID плейлиста",
    playlistNotFound: "Плейлист не знайдено",
    deleteTrackConfirm: "Видалити трек \"%s\"? Файли також будуть видалені з Cloudflare.",
    text: "📄",
    uploaded: "Завантажено",
    added: "Додано",
    noTracksAvailable: "Немає доступних треків для додавання",
    onlyAddOwnPlaylist: "Ви можете додавати треки лише до своїх плейлистів",
    notAllowedModify: "Вам не дозволено змінювати цей плейлист",
    noPermissionModify: "У вас немає дозволу на зміну цього плейлиста",
    failedFetchPlaylist: "Не вдалося отримати плейлист",
    failedOpenPlaylist: "Не вдалося відкрити плейлист",
    failedLoadTracks: "Не вдалося завантажити треки",
    noTracksSelected: "Не вибрано треків",
    noPlaylistSelected: "Не вибрано плейлист",
    alreadyInPlaylist: "Вибрані треки вже є в цьому плейлисті",
    addFailed: "Додавання не вдалося — перевірте консоль",
    removeTrackConfirm: "Видалити цей трек з плейлиста?",
    removeFailed: "Видалення не вдалося",
    selectOneField: "Виберіть принаймні одне поле для зміни",
    filesReplaced: "Файли успішно замінено!",
    replaceError: "Помилка заміни",
    uploadFailed: "Завантаження не вдалося",
    noTrackSelected: "Не вибрано трек",
    webShareNotSupported: "Web Share не підтримується",
    checkOut: "Слухай",
    track: "Трек",
    downloadFailed: "Завантаження не вдалося",
    audioNotFound: "Аудіо не знайдено",
    downloadError: "Помилка завантаження",
    updateFailed: "Оновлення не вдалося",
    comment: "Коментар",
    emoji: "Емодзі",
    loading: "Завантаження",
    trackName: "Назва треку",
    title: "Назва",
    home: "Головна",
    background: "Фон",
    add: "Додати",
    likedTracks: "Улюблені",
    feedback: "Зворотний зв'язок",
    feedbackTitle: "Зворотний зв'язок",
    feedbackSubtitle: "Напишіть нам пропозицію, повідомте про помилку або поділіться думкою",
    feedbackType: "Тип повідомлення",
    feedbackSuggestion: "💡 Пропозиція",
    feedbackRecommendation: "⭐ Рекомендація",
    feedbackBug: "🐛 Баг",
    feedbackOther: "❓ Інше",
    feedbackPlaceholder: "Опишіть свою думку...",
    feedbackMessage: "Повідомлення *",
    feedbackEmail: "Email (опціонально)",
    feedbackSubmit: "Надіслати",
    myFeedback: "Мої фідбеки",
    feedbackHistory: "Історія фідбеків",
    feedbackHistorySubtitle: "Ваші надіслані повідомлення та відповіді",
    noFeedback: "Немає повідомлень",
    statusUnread: "🔴 Не прочитано",
    statusInProgress: "🟠 В роботі",
    statusDone: "🟢 Зроблено",
    statusRejected: "⚪ Відхилено",
    statusRead: "💜 Прочитано",
    allFeedback: "Всі фідбеки",
    feedbackSent: "✅ Повідомлення надіслано! Дякуємо за зворотний зв'язок.",
    feedbackError: "❌ Помилка надсилання. Спробуйте пізніше.",
    feedbackRequired: "❌ Будь ласка, напишіть повідомлення",
    feedbackSending: "Надсилання...",
    deleteFeedbackConfirm: "Видалити це повідомлення?",
    deleteFeedbackError: "Помилка видалення",
    updateStatusError: "Помилка оновлення статусу",
    loadingHistoryError: "Помилка завантаження історії",
    feedbackRestrictedTitle: "🔒 Доступ обмежено",
    feedbackRestrictedText: "Надсилання відгуків доступне лише для зареєстрованих користувачів.",
    feedbackRestrictedLogin: "Увійти",
    feedbackRestrictedClose: "Закрити",

  },
  es: {
    updateAvailable: "🔄 Actualización disponible — toque para recargar",
    searchPlaceholder: "Buscar: título, artista o género",
    searchLyricsPlaceholder: "Buscar: letra",
    allGenres: "Todos los géneros",
    showMusic: "Mostrar",
    sortDefault: "📅 Por defecto",
    sortPlaysDesc: "▲ Reproducciones",
    sortPlaysAsc: "▼ Reproducciones",
    sortLikesDesc: "▲ Me gusta",
    sortLikesAsc: "▼ Me gusta",
    sortTitleAsc: "A-Z Título",
    sortTitleDesc: "Z-A Título",
    dragToReorder: "Arrastra las pistas para reordenar",
    uploadTrack: "⬆ Subir pista",
    uploadPartnerTrack: "🎧 Subir tu canción",
    exportJson: "📦 Exportar JSON",
    resetPlays: "🔄 Reiniciar reproducciones",
    uploadAdminOnly: "Solo yo subo",
    uploadPartnerOnly: "Yo + otra persona",
    uploadEveryone: "Todos pueden subir",
    loadingTracks: "⏳ Cargando pistas...",
    sequential: "Secuencial 🔁",
    random: "Aleatorio 🔀",
    volume: "Volumen",
    text: "📄",
    comments: "Comentarios",
    share: "Compartir",
    download: "Descargar",
    close: "Cerrar",
    cancel: "Cancelar",
    send: "Enviar",
    save: "💾 Guardar",
    copy: "📋 Copiar",
    copied: "✅ ¡Copiado!",
    edit: "✏️ Editar",
    addTrack: "Añadir pista",
    trackTitle: "Título de la pista",
    mp3Link: "Enlace MP3 (GitHub raw)",
    coverUrl: "URL de la portada",
    genres: "Géneros",
    lyrics: "Letra",
    fullText: "Texto completo",
    noComments: "Sin comentarios",
    writeComment: "Escribe un comentario...",
    deleteConfirm: "¿Eliminar este comentario?",
    commentSaved: "💬 ¡Comentario guardado!",
    commentError: "❌ Error al guardar comentario",
    noTracks: "Sin pistas",
    createFile: "Crea el archivo <code>tracks.json</code> en la raíz del repositorio",
    orAdd: "O añade mediante <strong>?admin</strong>",
    required: "Título, MP3 y portada son obligatorios",
    exported: "Exportado",
    tracks: "pistas!",
    uploadGithub: "Sube tracks.json a GitHub",
    refreshPage: "Actualiza la página en todos los dispositivos",
    plays: "reproducciones",
    playlists: "Listas de reproducción",
    myTracks: "Mis pistas",
    allTracks: "Todas las pistas",
    playlistName: "Nombre de la lista",
    createPlaylist: "Crear lista",
    addToPlaylist: "Añadir a lista",
    removeFromPlaylist: "Quitar de lista",
    visibility: "Visibilidad",
    public: "🌍 Público",
    partner: "♥ Solo pareja",
    hidden: "🔒 Oculto (solo yo)",
    songsInPlaylist: "canciones",
    changeCover: "Cambiar portada",
    addSongsToPlaylist: "Añadir canciones a lista",
    selectPlaylist: "Seleccionar lista",
    noPlaylists: "Aún no hay listas",
    likedSongs: "❤️ Canciones favoritas",
    showLikedOnly: "Mostrar solo favoritas",
    showAll: "Mostrar todo",
    deletePlaylist: "Eliminar lista",
    deletePlaylistConfirm: "¿Eliminar esta lista? Las canciones permanecerán en el sitio.",
    songVisibility: "Visibilidad de la canción",
    showToAll: "Mostrar a todos",
    showToMe: "Mostrar solo a mí",
    showToPartner: "Mostrar a mí y a mi pareja",
    userUpload: "Subir tu canción",
    uploadYourSong: "Subir tu canción",
    songTitle: "Título",
    songArtist: "Artista",
    songGenre: "Género",
    upload: "Subir",
    deleteTrack: "Eliminar pista",
    replaceTrackFiles: "🔄 Reemplazar archivos de pista",
    statsWillStay: "Las estadísticas (me gusta, reproducciones) se conservarán",
    newMp3Optional: "Nuevo archivo MP3 (opcional)",
    newCoverOptional: "Nueva imagen de portada (opcional)",
    replace: "Reemplazar",
    enter: "Entrar",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    newTracksShort: "NUEVO",
    uploadShort: "Subir",
    filterAllSongs: "🎧 Todas",
    filterMySongs: "👤 Mis pistas",
    filterPartner: "💑 Pareja",
    filterHidden: "🔒 Ocultas",
    filterPartnerOnly: "♥ Solo pareja",
    filterAdmin: "👑 Admin",
    filterPartnerOnlyMe: "🔒 Solo para mí",
    multiSelect: "Selección múltiple",
    uploadSuccess: "✅ ¡Canción subida!",
    uploadError: "❌ Error: ",
    uploading: "⏳ Subiendo...",
    uploadBtn: "Subir",
    likedTracks: "Favoritos",
    downloadRestricted: "Descarga restringida",
    downloadRestrictedText: "La descarga de pistas está disponible solo para usuarios registrados",
    createAccount: "Crear cuenta",
    create: "Crear",
    email: "Email",
    password: "Contraseña",
    passwordMin: "Contraseña (mín 6 caracteres)",
    confirmPassword: "Confirmar contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    sendResetEmail: "Enviar email de restablecimiento",
    backToLogin: "Volver al inicio de sesión",
    searchGenre: "Buscar género",
    searchTracks: "Buscar pistas...",
    coverImage: "Imagen de portada",
    darkGradient: "Degradado oscuro",
    purpleGradient: "Degradado púrpura",
    blueGradient: "Degradado azul",
    greenGradient: "Degradado verde",
    orangeGradient: "Degradado naranja",
    pinkGradient: "Degradado rosa",
    solidColor: "Color sólido",
    hideTracksFromHome: "Ocultar pistas de la página principal",
    hiddenFromHome: "Oculto de inicio",
    addTracksToPlaylist: "Añadir pistas a la lista",
    selectAll: "Seleccionar todo",
    addSelected: "Añadir seleccionados",
    previous: "Anterior",
    next: "Siguiente",
    playPause: "Reproducir/Pausa",
    openFullText: "Abrir texto completo",
    like: "Me gusta",
    dislike: "No me gusta",
    visualizer: "Visualizador",
    shareTrack: "Compartir pista",
    copyLink: "Copiar enlace",
    copyToClipboard: "Copiar al portapapeles",
    shareTo: "Compartir en",
    noLyrics: "Sin letra",
    anonymous: "Anónimo",
    writeCommentFirst: "Escribe un comentario primero",
    errorSendingComment: "Error al enviar comentario",
    saveFailed: "Error al guardar",
    failedToSaveLyrics: "Error al guardar la letra",
    playlistIdMissing: "Falta ID de lista",
    playlistNotFound: "Lista no encontrada",
    deleteTrackConfirm: "¿Eliminar pista \"%s\"? Los archivos también se eliminarán de Cloudflare.",
    text: "📄",
    uploaded: "Subido",
    added: "Añadido",
    noTracksAvailable: "No hay pistas disponibles para añadir",
    onlyAddOwnPlaylist: "Solo puedes añadir pistas a listas que hayas creado",
    notAllowedModify: "No tienes permiso para modificar esta lista",
    noPermissionModify: "No tienes permiso para modificar esta lista",
    failedFetchPlaylist: "Error al obtener la lista",
    failedOpenPlaylist: "Error al abrir la lista",
    failedLoadTracks: "Error al cargar las pistas",
    noTracksSelected: "No hay pistas seleccionadas",
    noPlaylistSelected: "No hay lista seleccionada",
    alreadyInPlaylist: "Las pistas seleccionadas ya están en esta lista",
    addFailed: "Error al añadir — revisa la consola",
    removeTrackConfirm: "¿Quitar esta pista de la lista?",
    removeFailed: "Error al quitar",
    selectOneField: "Selecciona al menos un campo para cambiar",
    filesReplaced: "¡Archivos reemplazados con éxito!",
    replaceError: "Error al reemplazar",
    uploadFailed: "Error al subir",
    noTrackSelected: "No hay pista seleccionada",
    webShareNotSupported: "Web Share no es compatible",
    checkOut: "Escucha",
    track: "Pista",
    downloadFailed: "Error al descargar",
    audioNotFound: "Audio no encontrado",
    downloadError: "Error de descarga",
    updateFailed: "Error al actualizar",
    comment: "Comentario",
    emoji: "Emoji",
    loading: "Cargando",
    trackName: "Nombre de la pista",
    title: "Título",
    home: "Inicio",
    background: "Fondo",
    add: "Añadir",
    likedTracks: "Favoritos",
    feedback: "Comentarios",
    feedbackTitle: "Comentarios",
    feedbackSubtitle: "Envíanos una sugerencia, reporta un error o comparte tus pensamientos",
    feedbackType: "Tipo de mensaje",
    feedbackSuggestion: "💡 Sugerencia",
    feedbackRecommendation: "⭐ Recomendación",
    feedbackBug: "🐛 Error",
    feedbackOther: "❓ Otro",
    feedbackMessage: "Mensaje *",
    feedbackEmail: "Email (opcional)",
    feedbackSubmit: "Enviar",
    myFeedback: "Mis comentarios",
    feedbackHistory: "Historial de comentarios",
    feedbackHistorySubtitle: "Tus mensajes enviados y respuestas",
    noFeedback: "Sin mensajes",
    statusUnread: "🔴 No leído",
    statusInProgress: "🟠 En progreso",
    statusDone: "🟢 Hecho",
    statusRejected: "⚪ Rechazado",
    statusRead: "💜 Leído",
    allFeedback: "Todos los comentarios",
    feedbackSent: "✅ ¡Mensaje enviado! Gracias por tu comentario.",
    feedbackError: "❌ Error al enviar. Intenta más tarde.",
    feedbackRequired: "❌ Por favor escribe un mensaje",
    feedbackSending: "Enviando...",
    deleteFeedbackConfirm: "¿Eliminar este mensaje?",
    deleteFeedbackError: "Error al eliminar",
    updateStatusError: "Error al actualizar estado",
    loadingHistoryError: "Error al cargar historial",
    feedbackSuggestion: "💡 Sugerencia",
    feedbackRecommendation: "⭐ Recomendación",
    feedbackBug: "🐛 Error",
    feedbackOther: "❓ Otro",
    feedbackPlaceholder: "Describe tu pensamiento...",
    feedbackRestrictedTitle: "🔒 Acceso restringido",
    feedbackRestrictedText: "Enviar comentarios está disponible solo para usuarios registrados.",
    feedbackRestrictedLogin: "Iniciar sesión",
    feedbackRestrictedClose: "Cerrar",

  },
};

let currentLang = localStorage.getItem('siteLanguage') || 'en';

function t(key) {
  return translations[currentLang]?.[key] || translations.en[key] || key;
}

function switchLanguage(lang) {
  window.currentLang = lang;
  localStorage.setItem('siteLanguage', lang);

  // Переводим textContent
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (key && translations[lang] && translations[lang][key]) {
      el.textContent = translations[lang][key];
    }
  });

  // Переводим placeholder'ы
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.dataset.i18nPlaceholder;
    if (key && translations[lang] && translations[lang][key]) {
      el.placeholder = translations[lang][key];
    }
  });

  // 🔥 Переводим title-атрибуты
  document.querySelectorAll('[data-i18n-title]').forEach(el => {
    const key = el.dataset.i18nTitle;
    if (key && translations[lang] && translations[lang][key]) {
      el.title = translations[lang][key];
    }
  });

  // Обновляем кнопку логина
  if (typeof refreshLoginBtn === 'function') {
    refreshLoginBtn();
  }

  // Placeholder'ы поиска
  const siteSearch = document.getElementById('siteSearch');
  const lyricsSearch = document.getElementById('lyricsSearch');
  if (siteSearch) siteSearch.placeholder = t('searchPlaceholder') || 'Search: title, artist or genre';
  if (lyricsSearch) lyricsSearch.placeholder = t('searchLyricsPlaceholder') || 'Search: lyrics';
}

function applyTranslations() {
  // placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(node => {
    const key = node.dataset.i18nPlaceholder;
    if (key) node.placeholder = t(key);
  });

  // elements with text
  document.querySelectorAll('[data-i18n]').forEach(node => {
    const key = node.dataset.i18n;
    if (key) node.textContent = t(key);
  });

  // special cases
  const siteSearch = document.getElementById('siteSearch');
  if (siteSearch) siteSearch.placeholder = t('searchPlaceholder');

  const lyricsSearch = document.getElementById('lyricsSearch');
  if (lyricsSearch) lyricsSearch.placeholder = t('searchLyricsPlaceholder');

  const emptyGenre = document.querySelector('#siteGenre option[value=""]');
  if (emptyGenre) emptyGenre.textContent = t('allGenres');

  // upload permission select with arrow prefix
  document.querySelectorAll('#upload-permission-select option[data-i18n]').forEach(opt => {
    opt.textContent = '⬆ ' + t(opt.dataset.i18n);
  });

  // play-count text node
  document.querySelectorAll('.play-count').forEach(node => {
    const textNode = Array.from(node.childNodes).find(n => n.nodeType === 3 && n.textContent.trim());
    if (textNode) textNode.textContent = ' ' + t('plays');
  });
}
