const translations = {
  en: {
    searchPlaceholder: "Search: title, artist or genre",
    allGenres: "All genres",
    uploadTrack: "⬆ Upload Track",
    uploadPartnerTrack: "🎧 Upload your song",
    exportJson: "📦 Export JSON",
    resetPlays: "🔄 Reset Plays",
    uploadAdminOnly: "I upload only",
    uploadPartnerOnly: "Me + second person",
    uploadEveryone: "Everyone can upload",
    loadingTracks: "⏳ Loading tracks...",
    sequential: "Sequential 🔁",
    random: "Random 🔀",
    volume: "Volume",
    text: "📄",
    comments: "Comments",
    share: "Share",
    download: "Download",
    close: "Close",
    cancel: "Cancel",
    send: "Send",
    save: "💾 Save",
    copy: "📋 Copy",
    copied: "✅ Copied!",
    edit: "✏️ Edit",
    addTrack: "Add Track",
    trackTitle: "Track title",
    mp3Link: "MP3 link (GitHub raw)",
    coverUrl: "Cover image URL",
    genres: "Genres",
    lyrics: "Lyrics",
    fullText: "Full text",
    noComments: "No comments",
    writeComment: "Write a comment...",
    deleteConfirm: "Delete this comment?",
    commentSaved: "💬 Comment saved!",
    commentError: "❌ Comment save error",
    noTracks: "No tracks",
    createFile: "Create <code>tracks.json</code> file in repository root",
    orAdd: "Or add via <strong>?admin</strong>",
    required: "Title, MP3 and cover are required",
    exported: "Exported",
    tracks: "tracks!",
    uploadGithub: "Upload tracks.json to GitHub",
    refreshPage: "Refresh page on all devices",
    plays: "plays",
    playlists: "Playlists",
    myTracks: "My Tracks",
    allTracks: "All Tracks",
    playlistName: "Playlist name",
    createPlaylist: "Create Playlist",
    addToPlaylist: "Add to Playlist",
    removeFromPlaylist: "Remove from Playlist",
    visibility: "Visibility",
    public: "🌍 Public",
    partner: "♥ Partner only",
    hidden: "🔒 Hidden (only me)",
    songsInPlaylist: "songs",
    changeCover: "Change Cover",
    addSongsToPlaylist: "Add Songs to Playlist",
    selectPlaylist: "Select Playlist",
    noPlaylists: "No playlists yet",
    likedSongs: "❤️ Liked Songs",
    showLikedOnly: "Show Liked Only",
    showAll: "Show All",
    deletePlaylist: "Delete Playlist",
    deletePlaylistConfirm: "Delete this playlist? Songs will remain on the site.",
    songVisibility: "Song Visibility",
    showToAll: "Show to All",
    showToMe: "Show Only to Me",
    showToPartner: "Show to Me & Partner",
    userUpload: "Upload your song",
    uploadYourSong: "Upload your song",
    songTitle: "Title",
    songArtist: "Artist",
    songGenre: "Genre",
    upload: "Upload",
    deleteTrack: "Delete track",
    replaceTrackFiles: "🔄 Replace track files",
    statsWillStay: "Statistics (likes, plays) will be preserved",
    newMp3Optional: "New MP3 file (optional)",
    newCoverOptional: "New cover image (optional)",
    replace: "Replace",
    enter: "Enter",
    login: "Login",
    logout: "Logout",
    newTracksShort: "NEW",
    uploadShort: "Upload",
    filterAllSongs: "All songs",
    filterMySongs: "My songs",
    filterPartner: "Partner",
    filterHidden: "Hidden from all",
    filterPartnerOnly: "Partner only",
    filterAdmin: "Admin",
  },
  pl: {
    searchPlaceholder: "Szukaj: tytuł, artysta lub gatunek",
    allGenres: "Wszystkie gatunki",
    uploadTrack: "⬆ Dodaj utwór",
    uploadPartnerTrack: "🎧 Dodaj swoją piosenkę",
    exportJson: "📦 Eksportuj JSON",
    resetPlays: "🔄 Resetuj Odsłuchy",
    uploadAdminOnly: "Dodaje tylko ja",
    uploadPartnerOnly: "Ja + druga osoba",
    uploadEveryone: "Moga dodawac wszyscy",
    loadingTracks: "⏳ Ładowanie utworów...",
    sequential: "Kolejno 🔁",
    random: "Losowo 🔀",
    volume: "Głośność",
    text: "📄",
    comments: "Komentarze",
    share: "Udostępnij",
    download: "Pobierz",
    close: "Zamknij",
    cancel: "Anuluj",
    send: "Wyślij",
    save: "💾 Zapisz",
    copy: "📋 Kopiuj",
    copied: "✅ Skopiowano!",
    edit: "✏️ Edytuj",
    addTrack: "Dodaj utwór",
    trackTitle: "Tytuł utworu",
    mp3Link: "Link do MP3 (GitHub raw)",
    coverUrl: "Adres URL okładki",
    genres: "Gatunki",
    lyrics: "Tekst piosenki",
    fullText: "Pełny tekst",
    noComments: "Brak komentarzy",
    writeComment: "Napisz komentarz...",
    deleteConfirm: "Usunąć ten komentarz?",
    commentSaved: "💬 Komentarz zapisany!",
    commentError: "❌ Błąd zapisu komentarza",
    noTracks: "Brak utworów",
    createFile: "Utwórz plik <code>tracks.json</code> w katalogu głównym",
    orAdd: "Lub dodaj przez <strong>?admin</strong>",
    required: "Tytuł, MP3 i okładka są wymagane",
    exported: "Wyeksportowano",
    tracks: "utworów!",
    uploadGithub: "Prześlij tracks.json do GitHub",
    refreshPage: "Odśwież stronę na wszystkich urządzeniach",
    plays: "odtworzeń",
    playlists: "Playlisty",
    myTracks: "Moje utwory",
    allTracks: "Wszystkie utwory",
    playlistName: "Nazwa listy",
    createPlaylist: "Utwórz Listę",
    addToPlaylist: "Dodaj do listy",
    removeFromPlaylist: "Usuń z listy",
    visibility: "Widoczność",
    public: "🌍 Publiczna",
    partner: "♥ Tylko dla partnera",
    hidden: "🔒 Ukryta (tylko ja)",
    songsInPlaylist: "utworów",
    changeCover: "Zmień okładkę",
    addSongsToPlaylist: "Dodaj utwory do listy",
    selectPlaylist: "Wybierz listę",
    noPlaylists: "Brak list odtwarzania",
    likedSongs: "❤️ Polubione utwory",
    showLikedOnly: "Pokaż tylko polubione",
    showAll: "Pokaż wszystkie",
    deletePlaylist: "Usuń listę",
    deletePlaylistConfirm: "Usunąć tę listę? Utwwory pozostaną na stronie.",
    songVisibility: "Widoczność utworu",
    showToAll: "Pokaż wszystkim",
    showToMe: "Pokaż tylko mnie",
    showToPartner: "Pokaż mnie i partnera",
    userUpload: "Dodaj swoją piosenkę",
    uploadYourSong: "Dodaj swoją piosenkę",
    songTitle: "Tytuł",
    songArtist: "Autor",
    songGenre: "Gatunek",
    upload: "Dodaj",
    replaceTrackFiles: "🔄 Zmień pliki utworu",
    statsWillStay: "Statystyki (polubienia, odsłuchy) zostaną zachowane",
    newMp3Optional: "Nowy plik MP3 (opcjonalnie)",
    newCoverOptional: "Nowa okładka (opcjonalnie)",
    replace: "Zmień",
    deleteTrack: "Usuń utwór",
    enter: "Wejdź",
    login: "Zaloguj",
    logout: "Wyloguj",
    newTracksShort: "NOWE",
    uploadShort: "Dodaj",
    filterAllSongs: "Wszystkie",
    filterMySongs: "Moje",
    filterPartner: "Partner",
    filterHidden: "Ukryte",
    filterPartnerOnly: "Tylko partner",
    filterAdmin: "Admin",
  },
  ua: {
    searchPlaceholder: "Пошук: назва, виконавець або жанр",
    allGenres: "Усі жанри",
    uploadTrack: "⬆ Завантажити трек",
    uploadPartnerTrack: "🎧 Завантажити свою пісню",
    exportJson: "📦 Експорт JSON",
    resetPlays: "🔄 Скинути Оглядання",
    uploadAdminOnly: "Завантажує тільки я",
    uploadPartnerOnly: "Я + друга особа",
    uploadEveryone: "Можуть завантажувати всі",
    loadingTracks: "⏳ Завантаження треків...",
    sequential: "По порядку 🔁",
    random: "Випадково 🔀",
    volume: "Гучність",
    text: "📄",
    comments: "Коментарі",
    share: "Поділитися",
    download: "Завантажити",
    close: "Закрити",
    cancel: "Скасувати",
    send: "Надіслати",
    save: "💾 Зберегти",
    copy: "📋 Копіювати",
    copied: "✅ Скопійовано!",
    edit: "✏️ Редагувати",
    addTrack: "Додати трек",
    trackTitle: "Назва треку",
    mp3Link: "Посилання на MP3 (GitHub raw)",
    coverUrl: "URL обкладинки",
    genres: "Жанри",
    lyrics: "Текст пісні",
    fullText: "Повний текст",
    noComments: "Немає коментарів",
    writeComment: "Напишіть коментар...",
    deleteConfirm: "Видалити цей коментар?",
    commentSaved: "💬 Коментар збережено!",
    commentError: "❌ Помилка збереження",
    noTracks: "Немає треків",
    createFile: "Створіть файл <code>tracks.json</code> у кореневій директорії",
    orAdd: "Або додайте через <strong>?admin</strong>",
    required: "Назва, MP3 та обкладинка обов'язкові",
    exported: "Експортовано",
    tracks: "треків!",
    uploadGithub: "Завантажте tracks.json на GitHub",
    refreshPage: "Оновіть сторінку на всіх пристроях",
    plays: "відтворень",
    playlists: "Плейлисти",
    myTracks: "Мої треки",
    allTracks: "Всі треки",
    playlistName: "Назва плейлиста",
    createPlaylist: "Створити плейлист",
    addToPlaylist: "Додати до плейлиста",
    removeFromPlaylist: "Видалити з плейлиста",
    visibility: "Видимість",
    public: "🌍 Публічний",
    partner: "♥ Тільки для партнера",
    hidden: "🔒 Прихований (лише я)",
    songsInPlaylist: "пісень",
    changeCover: "Змінити обкладинку",
    addSongsToPlaylist: "Додати пісні до плейлиста",
    selectPlaylist: "Виберіть плейлист",
    noPlaylists: "Плейлистів поки немає",
    likedSongs: "❤️ Улюблені пісні",
    showLikedOnly: "Показати лише улюблені",
    showAll: "Показати всі",
    deletePlaylist: "Видалити плейлист",
    deletePlaylistConfirm: "Видалити цей плейлист? Пісні залишаться на сайті.",
    songVisibility: "Видимість пісні",
    showToAll: "Показати всім",
    showToMe: "Показати лише мені",
    showToPartner: "Показати мені та партнеру",
    userUpload: "Завантажити свою пісню",
    uploadYourSong: "Завантажити свою пісню",
    songTitle: "Назва",
    songArtist: "Автор",
    songGenre: "Жанр",
    upload: "Завантажити",
    replaceTrackFiles: "🔄 Замінити файли треку",
    deleteTrack: "Видалити трек",
    statsWillStay: "Статистика (лайки, прослуховування) збережеться",
    newMp3Optional: "Новий MP3 файл (опціонально)",
    newCoverOptional: "Нове фото обкладинки (опціонально)",
    replace: "Замінити",
    enter: "Увійти",
    login: "Увійти",
    logout: "Вийти",
    newTracksShort: "НОВІ",
    uploadShort: "Додати",
    filterAllSongs: "Всі пісні",
    filterMySongs: "Мої пісні",
    filterPartner: "Партнер",
    filterHidden: "Приховані від всіх",
    filterPartnerOnly: "Видно тільки партнеру",
    filterAdmin: "Адмін",
  },
  es: {
    searchPlaceholder: "Buscar: título, artista o género",
    allGenres: "Todos los géneros",
    uploadTrack: "⬆ Subir pista",
    uploadPartnerTrack: "🎧 Subir tu canción",
    exportJson: "📦 Exportar JSON",
    resetPlays: "🔄 Reiniciar reproducciones",
    uploadAdminOnly: "Solo yo subo",
    uploadPartnerOnly: "Yo + otra persona",
    uploadEveryone: "Todos pueden subir",
    loadingTracks: "⏳ Cargando pistas...",
    sequential: "Secuencial 🔁",
    random: "Aleatorio 🔀",
    volume: "Volumen",
    text: "📄",
    comments: "Comentarios",
    share: "Compartir",
    download: "Descargar",
    close: "Cerrar",
    cancel: "Cancelar",
    send: "Enviar",
    save: "💾 Guardar",
    copy: "📋 Copiar",
    copied: "✅ ¡Copiado!",
    edit: "✏️ Editar",
    addTrack: "Añadir pista",
    trackTitle: "Título de la pista",
    mp3Link: "Enlace MP3 (GitHub raw)",
    coverUrl: "URL de la portada",
    genres: "Géneros",
    lyrics: "Letra",
    fullText: "Texto completo",
    noComments: "Sin comentarios",
    writeComment: "Escribe un comentario...",
    deleteConfirm: "¿Eliminar este comentario?",
    commentSaved: "💬 ¡Comentario guardado!",
    commentError: "❌ Error al guardar comentario",
    noTracks: "Sin pistas",
    createFile: "Crea el archivo <code>tracks.json</code> en la raíz del repositorio",
    orAdd: "O añade mediante <strong>?admin</strong>",
    required: "Título, MP3 y portada son obligatorios",
    exported: "Exportado",
    tracks: "pistas!",
    uploadGithub: "Sube tracks.json a GitHub",
    refreshPage: "Actualiza la página en todos los dispositivos",
    plays: "reproducciones",
    playlists: "Listas de reproducción",
    myTracks: "Mis pistas",
    allTracks: "Todas las pistas",
    playlistName: "Nombre de la lista",
    createPlaylist: "Crear lista",
    addToPlaylist: "Añadir a lista",
    removeFromPlaylist: "Quitar de lista",
    visibility: "Visibilidad",
    public: "🌍 Público",
    partner: "♥ Solo pareja",
    hidden: "🔒 Oculto (solo yo)",
    songsInPlaylist: "canciones",
    changeCover: "Cambiar portada",
    addSongsToPlaylist: "Añadir canciones a lista",
    selectPlaylist: "Seleccionar lista",
    noPlaylists: "Aún no hay listas",
    likedSongs: "❤️ Canciones favoritas",
    showLikedOnly: "Mostrar solo favoritas",
    showAll: "Mostrar todo",
    deletePlaylist: "Eliminar lista",
    deletePlaylistConfirm: "¿Eliminar esta lista? Las canciones permanecerán en el sitio.",
    songVisibility: "Visibilidad de la canción",
    showToAll: "Mostrar a todos",
    showToMe: "Mostrar solo a mí",
    showToPartner: "Mostrar a mí y a mi pareja",
    userUpload: "Subir tu canción",
    uploadYourSong: "Subir tu canción",
    songTitle: "Título",
    songArtist: "Artista",
    songGenre: "Género",
    upload: "Subir",
    deleteTrack: "Eliminar pista",
    replaceTrackFiles: "🔄 Reemplazar archivos de pista",
    statsWillStay: "Las estadísticas (me gusta, reproducciones) se conservarán",
    newMp3Optional: "Nuevo archivo MP3 (opcional)",
    newCoverOptional: "Nueva imagen de portada (opcional)",
    replace: "Reemplazar",
    enter: "Entrar",
    login: "Iniciar sesión",
    logout: "Cerrar sesión",
    newTracksShort: "NUEVO",
    uploadShort: "Subir",
    filterAllSongs: "Todas",
    filterMySongs: "Mis pistas",
    filterPartner: "Pareja",
    filterHidden: "Ocultas",
    filterPartnerOnly: "Solo pareja",
    filterAdmin: "Admin",
  }
};  

let currentLang = localStorage.getItem('language') || 'en';

function t(key) {
  return translations[currentLang]?.[key] || translations.en[key] || key;
}

function switchLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('language', lang);
  
  document.querySelectorAll('[id^="lang-"]').forEach(btn => btn.classList.remove('active'));
  const langBtn = document.getElementById('lang-' + lang);
  if (langBtn) langBtn.classList.add('active');
  
  applyTranslations();
}

function applyTranslations() {
  // placeholders
  document.querySelectorAll('[data-i18n-placeholder]').forEach(node => {
    const key = node.dataset.i18nPlaceholder;
    if (key) node.placeholder = t(key);
  });

  // elements with text
  document.querySelectorAll('[data-i18n]').forEach(node => {
    const key = node.dataset.i18n;
    if (key) node.textContent = t(key);
  });

  // options (general)
  document.querySelectorAll('option[data-i18n]').forEach(opt => {
    opt.textContent = t(opt.dataset.i18n);
  });

  // special cases
  const siteSearch = document.getElementById('siteSearch');
  if (siteSearch) siteSearch.placeholder = t('searchPlaceholder');

  const emptyGenre = document.querySelector('#siteGenre option[value=""]');
  if (emptyGenre) emptyGenre.textContent = t('allGenres');

  // upload permission select with arrow prefix
  document.querySelectorAll('#upload-permission-select option[data-i18n]').forEach(opt => {
    opt.textContent = '⬆ ' + t(opt.dataset.i18n);
  });

  // play-count text node
  document.querySelectorAll('.play-count').forEach(node => {
    const textNode = Array.from(node.childNodes).find(n => n.nodeType === 3 && n.textContent.trim());
    if (textNode) textNode.textContent = ' ' + t('plays');
  });
}
