// language_chat.js — Переводы для чата N1K∅
// Автоматически подключается к chat.html
// Язык берётся из localStorage (устанавливается на главной странице)

const TRANSLATIONS = {
  en: {
    deleted_at: 'Deleted:',
    access_denied: 'Access Restricted',
    access_desc: 'This chat is available only to authorized project members.',
    attach: 'Attach',
    audio_pause: '⏸️ Pause',
    audio_play: '▶️ Play',
    auto_logout_text: 'You have been inactive for 2 minutes. You have been logged out for security.',
    auto_logout_title: '⏱ Session expired',
    back_btn_title: '←',
    back_to_site: 'Back to site',
    cancel_edit: 'Cancel editing',
    ctx_delete: 'Delete',
    ctx_edit: 'Edit',
    ctx_pin: 'Pin',
    ctx_reply: 'Reply',
    delete_cancel: 'Cancel',
    delete_confirm_empty: 'Are you sure you want to empty the trash? This cannot be undone.',
    delete_confirm_forever: 'Are you sure you want to delete this message permanently?',
    delete_confirm_permanent: 'Are you sure you want to permanently delete this message?',
    delete_error: '❌ Error deleting messages',
    delete_hard: '🗑️ Permanently (cannot be recovered)',
    delete_soft: '📦 To trash (recoverable)',
    delete_success_permanent: '✅ Messages permanently deleted',
    delete_success_trash: '✅ Messages moved to trash',
    delete_text: 'Selected messages. Choose deletion method:',
    delete_title: 'Delete Messages',
    deleted_by_user: 'User',
    deleted_by_you: 'You',
    edit_title: 'Edit',
    edited: 'edited',
    emoji: 'Emoji',
    emoji_animals: 'Animals',
    emoji_category_animals: 'Animals',
    emoji_category_flags: 'Flags',
    emoji_category_food: 'Food', 
    emoji_category_symbols: 'Symbols',
    emoji_flags: 'Flags',
    emoji_food: 'Food',
    emoji_recent: 'Recently used',
    emoji_recent_empty: 'Your recent emojis will appear here',
    emoji_recent_empty_text: 'Your recent emojis will appear here',
    emoji_recent_title: 'Recently used',
    emoji_results: 'Search results', 
    emoji_search_empty: 'Nothing found',
    emoji_search_empty_text: 'Nothing found',
    emoji_search_results: 'Search results',
    emoji_smileys: 'Smileys & People',
    emoji_symbols: 'Symbols',
    empty_chat_desc: 'No messages yet. Write first — it\'s just between the two of you.',
    empty_chat_title: '💬',
    empty_trash_confirm: 'Are you sure you want to empty the trash? This action cannot be undone.',
    error_avatar: '❌ Failed to upload avatar',
    error_mic_access: '❌ No microphone access. Allow access in browser settings.',
    error_save: '❌ Failed to save changes',
    error_send: '❌ Failed to send message',
    error_upload: '❌ Failed to upload file',
    exit: '🚪',
    exit_btn: '🚪 Exit',
    exit_confirm: 'Exit chat?',
    file_audio: '🎵 Audio file: ',
    file_doc: '📄 File: ',
    file_fallback: 'file',
    file_image: '📷 Image',
    file_video: '🎬 Video',
    file_voice: '🎤 Voice message',
    img_viewer_close: 'Close',
    img_viewer_download: 'Download',
    input_placeholder: 'Message...',
    last_seen_on: 'last seen ',
    last_seen_today: 'last seen today at ',
    last_seen_yesterday: 'last seen yesterday at ',
    like_title: 'Like',
    message: 'Message',
    offline: 'offline',
    online: 'online',
    player_close: 'Close',
    player_default_title: 'Audio file',
    player_download: 'Download',
    player_voice_title: 'Voice message',
    profile: '👤',
    profile_avatar: 'Avatar (URL, letter or file)',
    profile_avatar_placeholder: 'Image URL or letter',
    profile_cancel: 'Cancel',
    profile_edit: '👤 Edit Profile',
    profile_name: 'Name',
    profile_name_placeholder: 'Your name',
    profile_save: 'Save',
    profile_uploading: '⏳ Uploading avatar...',
    rec_cancel: 'Cancel',
    rec_recording: 'Recording voice...',
    rec_send: 'Send',
    restore_all_confirm: 'Restore all messages from trash?',
    save_changes: 'Save changes',
    search: '🔍',
    search_error: 'Search error:',
    search_input_placeholder: 'Search messages...',
    search_no_results: 'Nothing found',
    search_recent: 'Recent',
    search_results_count: 'Found: ',
    select: '✓',
    send: 'Send',
    sender_you: 'You',
    status_delivered: 'Delivered',
    status_read: 'Read',
    status_sent: 'Sent',
    text_message: 'Text message',
    title: 'N1K∅ — Chat',
    today: 'Today',
    trash: '📦',
    trash_delete_forever: '🗑️ Delete forever',
    trash_delete_forever_btn: '🗑️ Delete forever',
    trash_empty: 'Trash is empty',
    trash_empty_btn: '🗑️ Empty trash',
    trash_empty_error: '❌ Error emptying trash',
    trash_empty_success: '✅ Trash emptied',
    trash_empty_text: 'Trash is empty',
    trash_error_loading: 'Loading error',
    trash_loading: 'Loading...',
    trash_loading_text: 'Loading...',
    trash_restore: '♻️ Restore',
    trash_restore_all: '♻️ Restore all',
    trash_restore_btn: '♻️ Restore',
    trash_restore_error: '❌ Error restoring message',
    trash_restore_success: '✅ Message restored',
    trash_title: '📦 Trash',
    typing: 'typing',
    video_download: '⬇ Download',
    voice: 'Voice',
    voice_message_title: 'Audio file',
    yesterday: 'Yesterday',
    emoji_category_recent: 'Recently used',
emoji_category_smileys: 'Smileys & Emotion',
emoji_category_people: 'People & Body',
emoji_category_animals: 'Animals & Nature',
emoji_category_food: 'Food & Drink',
emoji_category_activities: 'Activities',
emoji_category_travel: 'Travel & Places',
emoji_category_objects: 'Objects',
emoji_category_symbols: 'Symbols',
emoji_category_flags: 'Flags',
emoji_search: 'Search emoji',
emoji_search_results: 'Search results',
emoji_search_empty_text: 'No emoji found',
emoji_recent_title: 'Recently used',
emoji_recent_empty_text: 'No recent emoji',
ctx_copy: 'Copy',
copied: 'Copied',
copy_failed: 'Failed to copy',
delete_error_permanent: '❌ Error deleting',
reactions_coming_soon: 'Custom reactions feature coming soon',
    reply_to: 'Reply to',
    attachment: 'Attachment',
  },
  pl: {
    deleted_at: 'Usunięto:',
    access_denied: 'Dostęp ograniczony',
    access_desc: 'Ten czat jest dostępny tylko dla autoryzowanych członków projektu.',
    attach: 'Załącz',
    audio_pause: '⏸️ Pauza',
    audio_play: '▶️ Odtwórz',
    auto_logout_text: 'Byłeś nieaktywny przez 2 minuty. Zostałeś wylogowany ze względów bezpieczeństwa.',
    auto_logout_title: '⏱ Sesja wygasła',
    back_btn_title: '←',
    back_to_site: 'Powrót do strony',
    cancel_edit: 'Anuluj edycję',
    ctx_delete: 'Usuń',
    ctx_edit: 'Edytuj',
    ctx_pin: 'Przypnij',
    ctx_reply: 'Odpowiedz',
    delete_cancel: 'Anuluj',
    delete_confirm_empty: 'Czy na pewno chcesz opróżnić kosz? Tej operacji nie można cofnąć.',
    delete_confirm_forever: 'Czy na pewno chcesz trwale usunąć tę wiadomość?',
    delete_confirm_permanent: 'Czy na pewno chcesz trwale usunąć tę wiadomość?',
    delete_error: '❌ Błąd podczas usuwania wiadomości',
    delete_hard: '🗑️ Na zawsze (nie można odzyskać)',
    delete_soft: '📦 Do kosza (można odzyskać)',
    delete_success_permanent: '✅ Wiadomości trwale usunięte',
    delete_success_trash: '✅ Wiadomości przeniesione do kosza',
    delete_text: 'Wybrano wiadomości. Wybierz sposób usunięcia:',
    delete_title: 'Usuń wiadomości',
    deleted_by_user: 'Użytkownik',
    deleted_by_you: 'Ty',
    edit_title: 'Edytuj',
    edited: 'edyt.',
    emoji: 'Emoji',
    emoji_animals: 'Zwierzęta',
    emoji_category_animals: 'Zwierzęta',
    emoji_category_flags: 'Flagi',
    emoji_category_food: 'Jedzenie', 
    emoji_category_symbols: 'Symbole',
    emoji_flags: 'Flagi',
    emoji_food: 'Jedzenie',
    emoji_recent: 'Ostatnio używane',
    emoji_recent_empty: 'Tutaj pojawią się Twoje ostatnie emoji',
    emoji_recent_empty_text: 'Tutaj pojawią się Twoje ostatnie emoji',
    emoji_recent_title: 'Ostatnio używane',
    emoji_results: 'Wyniki wyszukiwania', 
    emoji_search_empty: 'Nic nie znaleziono',
    emoji_search_empty_text: 'Nic nie znaleziono',
    emoji_search_results: 'Wyniki wyszukiwania',
    emoji_smileys: 'Uśmiechy i ludzie',
    emoji_symbols: 'Symbole',
    empty_chat_desc: 'Brak wiadomości. Napisz pierwszy — to tylko między wami dwojgiem.',
    empty_chat_title: '💬',
    empty_trash_confirm: 'Czy na pewno chcesz opróżnić kosz? Tej operacji nie można cofnąć.',
    error_avatar: '❌ Nie udało się przesłać awatara',
    error_mic_access: '❌ Brak dostępu do mikrofonu. Zezwól na dostęp w ustawieniach przeglądarki.',
    error_save: '❌ Nie udało się zapisać zmian',
    error_send: '❌ Nie udało się wysłać wiadomości',
    error_upload: '❌ Nie udało się przesłać pliku',
    exit: '🚪',
    exit_btn: '🚪 Wyjdź',
    exit_confirm: 'Wyjdź z czatu?',
    file_audio: '🎵 Plik audio: ',
    file_doc: '📄 Plik: ',
    file_fallback: 'plik',
    file_image: '📷 Obraz',
    file_video: '🎬 Wideo',
    file_voice: '🎤 Wiadomość głosowa',
    img_viewer_close: 'Zamknij',
    img_viewer_download: 'Pobierz',
    input_placeholder: 'Wiadomość...',
    last_seen_on: 'był(a) online ',
    last_seen_today: 'był(a) online dzisiaj o ',
    last_seen_yesterday: 'był(a) online wczoraj o ',
    like_title: 'Lubię to',
    message: 'Wiadomość',
    offline: 'offline',
    online: 'online',
    player_close: 'Zamknij',
    player_default_title: 'Plik audio',
    player_download: 'Pobierz',
    player_voice_title: 'Wiadomość głosowa',
    profile: '👤',
    profile_avatar: 'Awatar (URL, litera lub plik)',
    profile_avatar_placeholder: 'URL obrazu lub litera',
    profile_cancel: 'Anuluj',
    profile_edit: '👤 Edytuj profil',
    profile_name: 'Imię',
    profile_name_placeholder: 'Twoje imię',
    profile_save: 'Zapisz',
    profile_uploading: '⏳ Przesyłanie awatara...',
    rec_cancel: 'Anuluj',
    rec_recording: 'Nagrywanie wiadomości głosowej...',
    rec_send: 'Wyślij',
    restore_all_confirm: 'Przywrócić wszystkie wiadomości z kosza?',
    save_changes: 'Zapisz zmiany',
    search: '🔍',
    search_error: 'Błąd wyszukiwania:',
    search_input_placeholder: 'Szukaj w wiadomościach...',
    search_no_results: 'Nic nie znaleziono',
    search_recent: 'Ostatnie',
    search_results_count: 'Znaleziono: ',
    select: '✓',
    send: 'Wyślij',
    sender_you: 'Ty',
    status_delivered: 'Dostarczono',
    status_read: 'Przeczytano',
    status_sent: 'Wysłano',
    text_message: 'Wiadomość tekstowa',
    title: 'N1K∅ — Czat',
    today: 'Dzisiaj',
    trash: '📦',
    trash_delete_forever: '🗑️ Usuń na zawsze',
    trash_delete_forever_btn: '🗑️ Usuń na zawsze',
    trash_empty: 'Kosz jest pusty',
    trash_empty_btn: '🗑️ Opróżnij kosz',
    trash_empty_error: '❌ Błąd podczas opróżniania kosza',
    trash_empty_success: '✅ Kosz opróżniony',
    trash_empty_text: 'Kosz jest pusty',
    trash_error_loading: 'Błąd ładowania',
    trash_loading: 'Ładowanie...',
    trash_loading_text: 'Ładowanie...',
    trash_restore: '♻️ Przywróć',
    trash_restore_all: '♻️ Przywróć wszystkie',
    trash_restore_btn: '♻️ Przywróć',
    trash_restore_error: '❌ Błąd podczas przywracania wiadomości',
    trash_restore_success: '✅ Wiadomość przywrócona',
    trash_title: '📦 Kosz',
    typing: 'pisze',
    video_download: '⬇ Pobierz',
    voice: 'Głos',
    voice_message_title: 'Plik audio',
    yesterday: 'Wczoraj',
    emoji_category_recent: 'Ostatnio używane',
emoji_category_smileys: 'Emotikony i uczucia',
emoji_category_people: 'Ludzie i ciało',
emoji_category_animals: 'Zwierzęta i natura',
emoji_category_food: 'Jedzenie i napoje',
emoji_category_activities: 'Aktywności',
emoji_category_travel: 'Podróże i miejsca',
emoji_category_objects: 'Przedmioty',
emoji_category_symbols: 'Symbole',
emoji_category_flags: 'Flagi',
emoji_search: 'Szukaj emoji',
emoji_search_results: 'Wyniki wyszukiwania',
emoji_search_empty_text: 'Nie znaleziono emoji',
emoji_recent_title: 'Ostatnio używane',
emoji_recent_empty_text: 'Brak ostatnich emoji',
ctx_copy: 'Kopiuj',
copied: 'Skopiowano',
copy_failed: 'Nie udało się skopiować',
delete_error_permanent: '❌ Błąd podczas usuwania',
reactions_coming_soon: 'Funkcja wyboru reakcji zostanie dodана',
    reply_to: 'Odpowiedz do',
    attachment: 'Załącznik',
  },
  ua: {
    deleted_at: 'Видалено:',
    access_denied: 'Доступ обмежено',
    access_desc: 'Цей чат доступний лише для авторизованих учасників проєкту.',
    attach: 'Прикріпити',
    audio_pause: '⏸️ Пауза',
    audio_play: '▶️ Відтворити',
    auto_logout_text: 'Ви були неактивні протягом 2 хвилин. Вас було виведено з системи з міркувань безпеки.',
    auto_logout_title: '⏱ Сеанс завершено',
    back_btn_title: '←',
    back_to_site: 'Повернутися на сайт',
    cancel_edit: 'Скасувати редагування',
    ctx_delete: 'Видалити',
    ctx_edit: 'Змінити',
    ctx_pin: 'Закріпити',
    ctx_reply: 'Відповісти',
    delete_cancel: 'Скасувати',
    delete_confirm_empty: 'Ви впевнені, що хочете очистити кошик? Цю дію неможливо скасувати.',
    delete_confirm_forever: 'Ви впевнені, що хочете безповоротно видалити це повідомлення?',
    delete_confirm_permanent: 'Ви впевнені, що хочете безповоротно видалити це повідомлення?',
    delete_error: '❌ Помилка під час видалення повідомлень',
    delete_hard: '🗑️ Безповоротно (неможливо відновити)',
    delete_soft: '📦 У кошик (можна відновити)',
    delete_success_permanent: '✅ Повідомлення безповоротно видалено',
    delete_success_trash: '✅ Повідомлення переміщено у кошик',
    delete_text: 'Обрано повідомлень. Оберіть спосіб видалення:',
    delete_title: 'Видалити повідомлення',
    deleted_by_user: 'Користувач',
    deleted_by_you: 'Ви',
    edit_title: 'Змінити',
    edited: 'ред.',
    emoji: 'Емодзі',
    emoji_animals: 'Тварини',
    emoji_category_animals: 'Тварини',
    emoji_category_flags: 'Прапори',
    emoji_category_food: 'Їжа', 
    emoji_category_symbols: 'Символи',
    emoji_flags: 'Прапори',
    emoji_food: 'Їжа',
    emoji_recent: 'Часто використовувані',
    emoji_recent_empty: 'Тут з\'являться ваші останні емодзі',
    emoji_recent_empty_text: 'Тут з\'являться ваші останні емодзі',
    emoji_recent_title: 'Часто використовувані',
    emoji_results: 'Результати пошуку', 
    emoji_search_empty: 'Нічого не знайдено',
    emoji_search_empty_text: 'Нічого не знайдено',
    emoji_search_results: 'Результати пошуку',
    emoji_smileys: 'Смайли та люди',
    emoji_symbols: 'Символи',
    empty_chat_desc: 'Повідомлень поки немає. Напишіть першим — це лише між вами двома.',
    empty_chat_title: '💬',
    empty_trash_confirm: 'Ви впевнені, що хочете очистити кошик? Цю дію неможливо скасувати.',
    error_avatar: '❌ Не вдалося завантажити аватар',
    error_mic_access: '❌ Немає доступу до мікрофона. Дозвольте доступ у налаштуваннях браузера.',
    error_save: '❌ Не вдалося зберегти зміни',
    error_send: '❌ Не вдалося надіслати повідомлення',
    error_upload: '❌ Не вдалося завантажити файл',
    exit: '🚪',
    exit_btn: '🚪 Вийти',
    exit_confirm: 'Вийти з чату?',
    file_audio: '🎵 Аудіофайл: ',
    file_doc: '📄 Файл: ',
    file_fallback: 'файл',
    file_image: '📷 Зображення',
    file_video: '🎬 Відео',
    file_voice: '🎤 Голосове повідомлення',
    img_viewer_close: 'Закрити',
    img_viewer_download: 'Завантажити',
    input_placeholder: 'Повідомлення...',
    last_seen_on: 'був(ла) в мережі ',
    last_seen_today: 'був(ла) в мережі сьогодні о ',
    last_seen_yesterday: 'був(ла) в мережі вчора о ',
    like_title: 'Подобається',
    message: 'Повідомлення',
    offline: 'офлайн',
    online: 'в мережі',
    player_close: 'Закрити',
    player_default_title: 'Аудіофайл',
    player_download: 'Завантажити',
    player_voice_title: 'Голосове повідомлення',
    profile: '👤',
    profile_avatar: 'Аватар (URL, літера або файл)',
    profile_avatar_placeholder: 'URL зображення або літера',
    profile_cancel: 'Скасувати',
    profile_edit: '👤 Редагувати профіль',
    profile_name: 'Ім\'я',
    profile_name_placeholder: 'Ваше ім\'я',
    profile_save: 'Зберегти',
    profile_uploading: '⏳ Завантаження аватара...',
    rec_cancel: 'Скасувати',
    rec_recording: 'Запис голосового...',
    rec_send: 'Надіслати',
    restore_all_confirm: 'Відновити всі повідомлення з кошика?',
    save_changes: 'Зберегти зміни',
    search: '🔍',
    search_error: 'Помилка пошуку:',
    search_input_placeholder: 'Пошук повідомлень...',
    search_no_results: 'Нічого не знайдено',
    search_recent: 'Нещодавні',
    search_results_count: 'Знайдено: ',
    select: '✓',
    send: 'Надіслати',
    sender_you: 'Ви',
    status_delivered: 'Доставлено',
    status_read: 'Прочитано',
    status_sent: 'Надіслано',
    text_message: 'Текстове повідомлення',
    title: 'N1K∅ — Чат',
    today: 'Сьогодні',
    trash: '📦',
    trash_delete_forever: '🗑️ Видалити назавжди',
    trash_delete_forever_btn: '🗑️ Видалити назавжди',
    trash_empty: 'Кошик порожній',
    trash_empty_btn: '🗑️ Очистити кошик',
    trash_empty_error: '❌ Помилка під час очищення кошика',
    trash_empty_success: '✅ Кошик очищено',
    trash_empty_text: 'Кошик порожній',
    trash_error_loading: 'Помилка завантаження',
    trash_loading: 'Завантаження...',
    trash_loading_text: 'Завантаження...',
    trash_restore: '♻️ Відновити',
    trash_restore_all: '♻️ Відновити всі',
    trash_restore_btn: '♻️ Відновити',
    trash_restore_error: '❌ Помилка під час відновлення повідомлення',
    trash_restore_success: '✅ Повідомлення відновлено',
    trash_title: '📦 Кошик',
    typing: 'друкує',
    video_download: '⬇ Завантажити',
    voice: 'Голос',
    voice_message_title: 'Аудіофайл',
    yesterday: 'Вчора',
    emoji_category_recent: 'Недавні',
emoji_category_smileys: 'Смайли та емоції',
emoji_category_people: 'Люди та тіло',
emoji_category_animals: 'Тварини та природа',
emoji_category_food: 'Їжа та напої',
emoji_category_activities: 'Діяльність',
emoji_category_travel: 'Подорожі та місця',
emoji_category_objects: 'Об\'єкти',
emoji_category_symbols: 'Символи',
emoji_category_flags: 'Прапори',
emoji_search: 'Пошук емодзі',
emoji_search_results: 'Результати пошуку',
emoji_search_empty_text: 'Емодзі не знайдено',
emoji_recent_title: 'Недавні',
emoji_recent_empty_text: 'Немає недавніх емодзі',
ctx_copy: 'Копіювати',
copied: 'Скопійовано',
copy_failed: 'Не вдалося скопіювати',
delete_error_permanent: '❌ Помилка під час видалення',
reactions_coming_soon: 'Функція вибору реакцій буде додана',
    reply_to: 'Відповідь до',
    attachment: 'Вкладення',
  },
  ru: {
    deleted_at: 'Удалено:',
    access_denied: 'Доступ ограничен',
    access_desc: 'Этот чат доступен только для авторизованных участников проекта.',
    attach: 'Прикрепить',
    audio_pause: '⏸️ Пауза',
    audio_play: '▶️ Воспроизвести',
    auto_logout_text: 'Вы были неактивны в течение 2 минут. Вы были выведены из системы в целях безопасности.',
    auto_logout_title: '⏱ Сеанс завершен',
    back_btn_title: '←',
    back_to_site: 'Вернуться на сайт',
    cancel_edit: 'Отменить редактирование',
    ctx_delete: 'Удалить',
    ctx_edit: 'Изменить',
    ctx_pin: 'Закрепить',
    ctx_reply: 'Ответить',
    delete_cancel: 'Отмена',
    delete_confirm_empty: 'Вы уверены, что хотите очистить корзину? Это действие нельзя отменить.',
    delete_confirm_forever: 'Вы уверены, что хотите безвозвратно удалить это сообщение?',
    delete_confirm_permanent: 'Вы уверены, что хотите безвозвратно удалить это сообщение?',
    delete_error: '❌ Ошибка при удалении сообщений',
    delete_hard: '🗑️ Безвозвратно (нельзя восстановить)',
    delete_soft: '📦 В корзину (можно восстановить)',
    delete_success_permanent: '✅ Сообщения безвозвратно удалены',
    delete_success_trash: '✅ Сообщения перемещены в корзину',
    delete_text: 'Выбрано сообщений. Выберите способ удаления:',
    delete_title: 'Удалить сообщения',
    deleted_by_user: 'Пользователь',
    deleted_by_you: 'Вы',
    edit_title: 'Редактировать',
    edited: 'изм.',
    emoji: 'Эмодзи',
    emoji_animals: 'Животные',
    emoji_category_animals: 'Животные',
    emoji_category_flags: 'Флаги',
    emoji_category_food: 'Еда', 
    emoji_category_symbols: 'Символы',
    emoji_flags: 'Флаги',
    emoji_food: 'Еда',
    emoji_recent: 'Часто используемые',
    emoji_recent_empty: 'Здесь появятся ваши последние эмодзи',
    emoji_recent_empty_text: 'Здесь появятся ваши последние эмодзи',
    emoji_recent_title: 'Часто используемые',
    emoji_results: 'Результаты поиска', 
    emoji_search_empty: 'Ничего не найдено',
    emoji_search_empty_text: 'Ничего не найдено',
    emoji_search_results: 'Результаты поиска',
    emoji_smileys: 'Смайлы и люди',
    emoji_symbols: 'Символы',
    empty_chat_desc: 'Сообщений пока нет. Напишите первым — это только между вами двоими.',
    empty_chat_title: '💬',
    empty_trash_confirm: 'Вы уверены, что хотите очистить корзину? Это действие нельзя отменить.',
    error_avatar: '❌ Не удалось загрузить аватар',
    error_mic_access: '❌ Нет доступа к микрофону. Разрешите доступ в настройках браузера.',
    error_save: '❌ Не удалось сохранить изменения',
    error_send: '❌ Не удалось отправить сообщение',
    error_upload: '❌ Не удалось загрузить файл',
    exit: '🚪',
    exit_btn: '🚪 Выйти',
    exit_confirm: 'Выйти из чата?',
    file_audio: '🎵 Аудиофайл: ',
    file_doc: '📄 Файл: ',
    file_fallback: 'файл',
    file_image: '📷 Изображение',
    file_video: '🎬 Видео',
    file_voice: '🎤 Голосовое сообщение',
    img_viewer_close: 'Закрыть',
    img_viewer_download: 'Скачать',
    input_placeholder: 'Сообщение...',
    last_seen_on: 'был(а) в сети ',
    last_seen_today: 'был(а) в сети сегодня в ',
    last_seen_yesterday: 'был(а) в сети вчера в ',
    like_title: 'Нравится',
    message: 'Сообщение',
    offline: 'офлайн',
    online: 'онлайн',
    player_close: 'Закрыть',
    player_default_title: 'Аудиофайл',
    player_download: 'Скачать',
    player_voice_title: 'Голосовое сообщение',
    profile: '👤',
    profile_avatar: 'Аватар (URL, буква или файл)',
    profile_avatar_placeholder: 'URL изображения или буква',
    profile_cancel: 'Отмена',
    profile_edit: '👤 Редактировать профиль',
    profile_name: 'Имя',
    profile_name_placeholder: 'Ваше имя',
    profile_save: 'Сохранить',
    profile_uploading: '⏳ Загружаем аватар...',
    rec_cancel: 'Отмена',
    rec_recording: 'Запись голосового...',
    rec_send: 'Отправить',
    restore_all_confirm: 'Восстановить все сообщения из корзины?',
    save_changes: 'Сохранить изменения',
    search: '🔍',
    search_error: 'Ошибка поиска:',
    search_input_placeholder: 'Поиск по сообщениям...',
    search_no_results: 'Ничего не найдено',
    search_recent: 'Недавние',
    search_results_count: 'Найдено: ',
    select: '✓',
    send: 'Отправить',
    sender_you: 'Вы',
    status_delivered: 'Доставлено',
    status_read: 'Прочитано',
    status_sent: 'Отправлено',
    text_message: 'Текстовое сообщение',
    title: 'N1K∅ — Чат',
    today: 'Сегодня',
    trash: '📦',
    trash_delete_forever: '🗑️ Удалить навсегда',
    trash_delete_forever_btn: '🗑️ Удалить навсегда',
    trash_empty: 'Корзина пуста',
    trash_empty_btn: '🗑️ Очистить корзину',
    trash_empty_error: '❌ Ошибка при очистке корзины',
    trash_empty_success: '✅ Корзина очищена',
    trash_empty_text: 'Корзина пуста',
    trash_error_loading: 'Ошибка загрузки',
    trash_loading: 'Загрузка...',
    trash_loading_text: 'Загрузка...',
    trash_restore: '♻️ Восстановить',
    trash_restore_all: '♻️ Восстановить все',
    trash_restore_btn: '♻️ Восстановить',
    trash_restore_error: '❌ Ошибка при восстановлении сообщения',
    trash_restore_success: '✅ Сообщение восстановлено',
    trash_title: '📦 Корзина удаленных сообщений',
    typing: 'печатает',
    video_download: '⬇ Скачать',
    voice: 'Голос',
    voice_message_title: 'Аудиофайл',
    yesterday: 'Вчера',
   emoji_category_recent: 'Недавние',
emoji_category_smileys: 'Смайлы и эмоции',
emoji_category_people: 'Люди и тело',
emoji_category_animals: 'Животные и природа',
emoji_category_food: 'Еда и напитки',
emoji_category_activities: 'Активность',
emoji_category_travel: 'Путешествия и места',
emoji_category_objects: 'Объекты',
emoji_category_symbols: 'Символы',
emoji_category_flags: 'Флаги',
emoji_search: 'Поиск эмодзи',
emoji_search_results: 'Результаты поиска',
emoji_search_empty_text: 'Ничего не найдено',
emoji_recent_title: 'Недавние',
emoji_recent_empty_text: 'Нет недавних эмодзи',               
ctx_copy: 'Копировать',
copied: 'Скопировано',
copy_failed: 'Не удалось скопировать',
delete_error_permanent: '❌ Ошибка при удалении',
reactions_coming_soon: 'Функция выбора новых реакций будет добавлена',
    reply_to: 'Ответ на',
    attachment: 'Вложение',
  },
};

// === Глобальная функция получения перевода ===
function t(key) {
  const lang = (typeof currentLang !== 'undefined' ? currentLang : 'en');
  return TRANSLATIONS[lang]?.[key] ?? TRANSLATIONS['en']?.[key] ?? key;
}

// === Экспорт для модулей (если нужно) ===
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TRANSLATIONS, t };
}
